name: vp-patterns/publish-charts
on:
  workflow_dispatch:
    inputs:
      SOURCE_TAG:
        required: true
        description: The tag of the helm chart repo to build
      SOURCE_REPO:
        required: true
        description: The helm chart repo
      TEMPLATE_DIR:
        required: false
        description: The path relative to the SOURCE_REPO where Chart.yaml and the templates directory is
        default: ""
      SOURCE_BRANCH_OVERRIDE:
        required: false
        description: If specified, checks out the head of this branch rather than the commit tagged by SOURCE_TAG
        default: ""

env:
  SOURCE_TAG: "${{ inputs.SOURCE_TAG }}"
  SOURCE_REPO: "${{ inputs.SOURCE_REPO }}"
  SOURCE_BRANCH_OVERRIDE: "${{ inputs.SOURCE_BRANCH_OVERRIDE }}"

jobs:
  update-charts:
    if: ${{ inputs.SOURCE_TAG }}
    runs-on: ubuntu-latest
    permissions: write-all
    # permissions:
    #   id-token: write
    #   contents: read
    steps:
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.1
      - name: clone helm repo
        env:
          SOURCE_BRANCH_OVERRIDE: ${{ inputs.SOURCE_BRANCH_OVERRIDE }}
        run: |-
          set -e
          if [ -n "${SOURCE_BRANCH_OVERRIDE}" ]; then
            git clone "https://github.com/${SOURCE_REPO}.git" \
              --branch "${SOURCE_BRANCH_OVERRIDE}" --single-branch helm-repo
          else
            git clone "https://github.com/${SOURCE_REPO}.git" \
              --branch "${SOURCE_TAG}" --single-branch helm-repo
          fi
      - name: helm package
        shell: bash
        run: |-
          set -euo pipefail
          helm package helm-repo/${{ inputs.TEMPLATE_DIR }}
      - name: upload helm package in release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: test-0.0.1.tgz
          asset_name: test-0.0.1.tgz
          tag: ${{ github.ref }}
          body: "test-0.0.1 yoohoo"
          overwrite: true
      - name: update helm index
        run: |-
          set -e
          helm repo index --url https://mbaldessari.github.io/vp-helm-charts/ --merge index.yaml .
          cat index.yaml
